/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-14 08:03:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String view=(String)request.getParameter("view");
	
	if(view == null){
		view="main.jsp";
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/index.css?ver=101\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/menubar.css?ver=200\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/section.css?ver=300\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<div class=\"event\">\r\n");
      out.write("\t\t\t\t주도 행사 알림바(참고 쇼핑몰:바이슬림)\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"backend\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">홈</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">즐겨찾기</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">바로가기</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp?view=login.jsp\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp?view=join.jsp\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">마이쇼핑</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"category-sub\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp?view=member_update.jsp\">회원정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">주문내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">관심상품</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">배송 주소록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">적립금</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">예치금</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">쿠폰</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">게시판 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">장바구니</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">주문조회</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터 & 이벤트</a></li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<form class=\"search\" action=\"\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t<img class=\"logo-img\" src=\"./images/snoopy.jpg\" alt=\"로고\"/>\r\n");
      out.write("\t\t\t\t<h1>쇼핑몰 이름</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"ss\">\r\n");
      out.write("\t\t\t\t<ul class=\"category\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">=</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">best</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">new</a></li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">top</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"category-sub\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">긴팔</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">맨투맨/후드</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">니트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">반팔</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">티셔츠</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">pants</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"category-sub\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">menu</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">menu</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">menumenu</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">menumenu</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">menumenumenu</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">shirt</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">outer</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">shoes</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">item</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, view , out, false);
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\tfooter\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
